module.exports = {
	GET_IMAGES: 'GET_IMAGES',
	GET_IMAGES_PENDING:'GET_IMAGES_PENDING',
	GET_IMAGES_FULFILLED: 'GET_IMAGES_FULFILLED',
	GET_TATTOO: 'GET_TATTOO',
	GET_TATTOO_PENDING: 'GET_TATTOO_PENDING',
	GET_TATTOO_FULFILLED: 'GET_TATTOO_FULFILLED',
	PICK_TATTOO: 'PICK_TATTOO',
	GO_BACK: 'GO_BACK'
}